baseURL = "https://project-allpix-squared.web.cern.ch/project-allpix-squared/"
languageCode = "en-us"
title = "Allpix Squared"
DefaultContentLanguage = "en"
theme = "allpix-squared-webtheme"
pygmentsUseClasses = true
pygmentCodeFences = true

[Params]
  subtitle = "Generic Pixel Detector Simulation Framework"
  commit = "https://gitlab.cern.ch/simonspa/allpix-squared-website/commit/"
  logo = "img/logo_small.png"
  favicon = "img/favicon.png"

[Author]
  name = "Daniel Hynds, Simon Spannagel, Koen Wolters"
  email = "allpix.squared@cern.ch"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 2

[[menu.main]]
    name = "Features"
    url = "page/features/"
    weight = 3

[[menu.main]]
    identifier = "doc"
    name = "Documentations"
    weight = 4

[[menu.main]]
    parent = "doc"
    name = "Online User Manual"
    url = "usermanual/allpix-manual.html"
    weight = 1

[[menu.main]]
    parent = "doc"
    name = "User Manual (PDF)"
    url = ""
    weight = 2

[[menu.main]]
    parent = "doc"
    name = "Code Reference"
    url = "reference/html"
    weight = 3

[[menu.main]]
    identifier = "resources"
    name = "Help & Resources"
    weight = 5

[[menu.main]]
    parent = "resources"
    name = "Repository"
    url = "https://gitlab.cern.ch/simonspa/allpix-squared"
    weight = 2

[[menu.main]]
    parent = "resources"
    name = "Issue Tracker"
    url = "https://gitlab.cern.ch/simonspa/allpix-squared/issues"
    weight = 1
