baseURL = "http://cern.ch/allpix-square/"
languageCode = "en-us"
title = "Allpix Squared"
DefaultContentLanguage = "en"
theme = "allpix-squared-webtheme"
pygmentsUseClasses = true
pygmentCodeFences = true

[Params]
  subtitle = "Generic Pixel Detector Simulation Framework"
  commit = "https://gitlab.cern.ch/simonspa/allpix-squared/website/tree/"
  logo = "img/logo_small.png"
  favicon = "img/favicon.png"

[Author]
  name = "Daniel Hynds, Simon Spannagel, Koen Wolters"
  email = "allpix.squared@cern.ch"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    identifier = "samples"
    name = "Examples"
    weight = 2

[[menu.main]]
    parent = "samples"
    name = "Big Image Sample"
    url = "post/2017-03-07-bigimg-sample"
    weight = 1

[[menu.main]]
    name = "Code Reference"
    url = "reference/html"
    weight = 4
