baseURL = "https://project-allpix-squared.web.cern.ch/project-allpix-squared/"
canonifyURLs = true
languageCode = "en-us"
title = "Allpix Squared"
DefaultContentLanguage = "en"
theme = "allpix-squared-webtheme"
pygmentsUseClasses = true
pygmentCodeFences = true

[Params]
  subtitle = "Generic Pixel Detector Simulation Framework"
  commit = "https://gitlab.cern.ch/allpix-squared/allpix-squared-website/commit/"
  logo = "img/logo_small.png"
  favicon = "img/favicon.png"

[Author]
  name = "The Allpix Squared Authors"
  email = "allpix.squared@cern.ch"

[[menu.main]]
    name = "News"
    url = ""
    weight = 1

[[menu.main]]
    identifier = "about"
    name = "About"
    weight = 2

[[menu.main]]
    parent = "about"
    name = "Introduction"
    url = "page/about/"
    weight = 1

[[menu.main]]
    parent = "about"
    name = "Features"
    url = "page/features/"
    weight = 2

[[menu.main]]
    parent = "about"
    name = "Installation"
    url = "page/installation/"
    weight = 3

[[menu.main]]
    parent = "about"
    name = "Screenshots"
    url = "page/screenshots/"
    weight = 4

[[menu.main]]
    identifier = "doc"
    name = "Documentation"
    weight = 3

[[menu.main]]
    parent = "doc"
    name = "Online User Manual"
    url = "usermanual/allpix-manual.html"
    weight = 1

[[menu.main]]
    parent = "doc"
    name = "User Manual (PDF)"
    url = "usermanual/allpix-manual.pdf"
    weight = 2

[[menu.main]]
    parent = "doc"
    name = "Code Reference"
    url = "reference"
    weight = 3

[[menu.main]]
    identifier = "resources"
    name = "Help & Resources"
    weight = 4

[[menu.main]]
    parent = "resources"
    name = "Download releases"
    url = "releases/"
    weight = 1

[[menu.main]]
    parent = "resources"
    name = "✉ Mailing Lists"
    url = "https://e-groups.cern.ch/e-groups/EgroupsSearch.do?searchValue=allpix-squared"
    weight = 2

[[menu.main]]
    parent = "resources"
    name = "Repository"
    url = "https://gitlab.cern.ch/allpix-squared/allpix-squared"
    weight = 5

[[menu.main]]
    parent = "resources"
    name = "Issue Tracker"
    url = "https://gitlab.cern.ch/allpix-squared/allpix-squared/issues"
    weight = 4
