baseURL = "http://cern.ch/allpix-square/"
languageCode = "en-us"
title = "Allpix Squared"

[Params]
  subtitle = "Generic Pixel Detector Simulation Framework"
  Author = "Simon Spannagel"
  commit = "https://gitlab.cern.ch/simonspa/allpix-squared/website/tree/"
  logo = "img/logo_small.png"
  favicon = "img/favicon.png"