baseURL = "https://project-allpix-squared.web.cern.ch/project-allpix-squared/"
languageCode = "en-us"
title = "Allpix Squared"
DefaultContentLanguage = "en"
theme = "allpix-squared-webtheme"
pygmentsUseClasses = true
pygmentCodeFences = true

[Params]
  subtitle = "Generic Pixel Detector Simulation Framework"
  commit = "https://gitlab.cern.ch/simonspa/allpix-squared/website/tree/"
  logo = "img/logo_small.png"
  favicon = "img/favicon.png"

[Author]
  name = "Daniel Hynds, Simon Spannagel, Koen Wolters"
  email = "allpix.squared@cern.ch"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    identifier = "resources"
    name = "Resources"
    weight = 2

[[menu.main]]
    parent = "resources"
    name = "Repository"
    url = "https://gitlab.cern.ch/simonspa/allpix-squared"
    weight = 1

[[menu.main]]
    parent = "resources"
    name = "Code Reference Manual"
    url = "reference/html"
    weight = 2

[[menu.main]]
    parent = "resources"
    name = "Issue Tracker"
    url = "https://gitlab.cern.ch/simonspa/allpix-squared/issues"
    weight = 3

[[menu.main]]
    name = "Code Reference"
    url = "reference/html"
    weight = 4
